### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by mattdryden** [beeficecream/YNABDashboard#1]
https://github.com/beeficecream/YNABDashboard/blob/f039d3fa864f23bf1e10882e213bf5cce1a75367/python/main.py#L26

I don't know too much Python but pretty sure this is mean't to be json_file and not file? (feel free to delete this)

p.s awesome Dashboard

**Comment by beeficecream** [comment]
Nah it needs to remain a .py file.  What issue are you having?

**Comment by spryor2** [comment]
I had this problem, too; created a pull #2 request for the fix.

**Comment by beeficecream** [comment]
Hey guys - disregard my initial comment, it was nonsense.  I was using an app to display GitHub that didn't properly display the code comment.

You are 100% correct, that line should reference json_file instead of file.  I'm updating source now.
